apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-service
  labels:
    app: weather-frontend
spec:
  type: LoadBalancer
  selector:
    app: weather-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
